[project]
name = "visualisation-group-65"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "dash>=2.14.0",
    "dash-bootstrap-components>=2.0.4",
    "numpy>=1.24.0",
    "pandas>=2.0.0",
    "plotly>=5.18.0",
]
